name: Code Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install uv (with cache dependency glob)
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: MyPy Type Analysis
        run: uv run mypy leaf_tab.py

      - name: Ruff Lint and Format Analysis
        run: uv run ruff check leaf_tab.py
